### ISSUE TITLE
Edna to receive holder rewards

### ISSUE THREAD

**Issue by nikoladimitroff** [trustfractal/protocol#148]

**Comment by shelbyd** [comment]
As I'm implementing this, I'm seeing another drawback. The main way I can see to implement this (without transaction hooks from Substrate), is to snapshot all balances at important intervals. The problem is that users could send balances in between snapshots and this code would be none the wiser.

As this is yet another in the world of problems with the approach of on-chain holder rewards, I think it's time to move to opt-in staking, despite the cost of making an additional UI in the wallet.

@nikoladimitroff We may want to treat this as a larger effort now, since it will have some UI and optional features that we may want to incrementally implement. One example is showing an estimated ROI when staking to help inform the user of if it's worth it for them. I'll still start implementing the on-chain parts under this issue.

**Comment by nikoladimitroff** [comment]
Replaced the holder program with a staking one
